import avatar from "../Assets/Img/avatar.png";
export const mockTherapists = [
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    rating: 4.5,
    img: avatar,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    img: avatar,
    rating: 4.5,
  },
  {
    id: 1,
    therapistName: "Ram Shyam",
    price: 3400,
    therapistPost: "Counselor",
    address: "Gwarko, Lalitpur",
    img: avatar,
    rating: 4.5,
  },
];
